version: '3.9'
services:
  app:
    build: .
    ports:
      - 4000:4000
    env_file:
      src/config/.env
    depends_on:
      - db
  db:
    image: postgres:10.16
    environment:
      POSTGRESS_USER: postgres
      POSTGRESS_PASSWORD: password
      POSTGRESS_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

      